2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_setup.py:_flush():68] Configure stats pid to 10522
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_setup.py:_flush():68] Loading settings from /home/zc355/.config/wandb/settings
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_setup.py:_flush():68] Loading settings from /home/zc355/Desktop/DL/DDPM/wandb/settings
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_init.py:_log_setup():528] Logging user logs to /home/zc355/Desktop/DL/DDPM/wandb/run-20241216_180533-4vulyyoz/logs/debug.log
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_init.py:_log_setup():529] Logging internal logs to /home/zc355/Desktop/DL/DDPM/wandb/run-20241216_180533-4vulyyoz/logs/debug-internal.log
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_init.py:init():644] calling init triggers
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0002, 'batch_size': 128, 'iterations': 10, 'log_to_wandb': True, 'log_rate': 1000, 'checkpoint_rate': 1000, 'log_dir': '~/ddpm_logs', 'project_name': 'DDPM_BIC', 'run_name': 'ddpm-2024-12-16-18-05', 'model_checkpoint': None, 'optim_checkpoint': None, 'schedule_low': 0.0001, 'schedule_high': 0.02, 'device': device(type='cuda'), 'num_timesteps': 1000, 'schedule': 'linear', 'loss_type': 'l2', 'use_labels': False, 'base_channels': 128, 'channel_mults': (1, 2, 2, 2), 'num_res_blocks': 2, 'time_emb_dim': 512, 'norm': 'gn', 'dropout': 0.1, 'activation': 'silu', 'attention_resolutions': (1,), 'ema_decay': 0.9999, 'ema_update_rate': 1}
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_init.py:init():680] starting backend
2024-12-16 18:05:33,961 INFO    MainThread:10522 [wandb_init.py:init():684] sending inform_init request
2024-12-16 18:05:33,964 INFO    MainThread:10522 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-16 18:05:33,964 INFO    MainThread:10522 [wandb_init.py:init():697] backend started and connected
2024-12-16 18:05:33,965 INFO    MainThread:10522 [wandb_init.py:init():790] updated telemetry
2024-12-16 18:05:33,967 INFO    MainThread:10522 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2024-12-16 18:05:34,208 ERROR   MainThread:10522 [wandb_init.py:init():849] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-16 18:05:34,208 ERROR   MainThread:10522 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/home/zc355/anaconda3/envs/py312_ddpm/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/zc355/anaconda3/envs/py312_ddpm/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-12-16 18:05:34,212 WARNING MsgRouterThr:10522 [router.py:message_loop():75] message_loop has been closed
